### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by BroehainIsHere** [arthurbambou/Randomly-Adding-Anything#7] opened 2019-09-21 19:36 UTC
With the Fabric loader, the game immediately crashes if I try to launch it. I have no idea what the problem could be; I'm using the latest build of Fabric at version 1.14.4, which the mod works with.

**Comment by h4tena** [comment] 2019-09-21 20:50
This happens to me too. Using the latest version of both Fabric and the mod.

**Comment by thecatcore** [comment] 2019-09-22 11:49
I can't reproduce the crash, can you both try again with the latest version of Fabric Loader and Fabric API ?

**Comment by oliviathevampire** [comment] 2019-09-22 12:11
might also happen because of old material file

**Comment by thecatcore** [comment] 2019-09-22 12:12
Next release will fix the problem

**Comment by BroehainIsHere** [comment] 2019-09-22 13:32
Nah man I'm being stupid, I forgot to install the API. Never used Fabric before now. Bit of a rookie mistake.

**Comment by thecatcore** [comment] 2019-09-22 13:59
So we can close this

**Closed as completed by thecatcore** 2019-09-22 13:59 UTC
