### ISSUE TITLE
the game will not generate any random ores or dimensions (Into world generation.)

### ISSUE THREAD

**Issue by GamerGrill127** [arthurbambou/Randomly-Adding-Anything#79] opened 2020-03-19 16:53 UTC
And its not like the game doesn't have the ores present in the game, it just won't incorporate them in to world generation. 
I've seen other people bring this up before, But they closed the issue without giving an answer that was useful.

I've heard something about setting a "regen" value to "true" (sorry if I'm using the incorrect language) in a .json folder, but no one has ever specified which one.

**Comment by ghost** [comment] 2020-03-19 17:00
The [Curseforge page](https://www.curseforge.com/minecraft/mc-mods/randomly-adding-anything) for the mod says which file you must modify to set the regen config:

> A: In the configs folder there is a raa.json5 document. If you set the "regen" property to true, new ores will generate each time you boot up minecraft until that setting is turned back to false.

Also, they are fully aware of this issue but don't know the cause, which is probably why they aren't `giving an answer that was useful`, as they are not sure themselves. 

Hopefully, this helped you a bit.

**Comment by oliviathevampire** [comment] 2020-04-04 11:45
Should be fixed in newest github release

**Closed as completed by oliviathevampire** 2020-04-04 11:45 UTC
